### PR TITLE
Update rake and nokogiri

### PR DESCRIPTION
**Pull request by mdimas**
Security updates. @change/pack-data

### CODE REVIEW

**Review by quaelin — APPROVED** [review]

**Comment by spacer59** [comment]
@mdimas I remember we were planning to deprecate this repo a few weeks ago, is that still the plan or is it being used elsewhere?

**Comment by mdimas** [comment]
@spacer59 as long as it isn't in use we can deprecate it. I wasn't sure where that conversation had landed, so I did these quick updates just in case.

**Comment by spacer59** [comment]
I have inventoried following repos and their submodules and did not find any `aws-swf` dependencies ; I don't see any active (or legacy) workflows in the AWS SWF console (unless I just don't have access).
- `etl_fluentd_events`: no `aws-swf` dependency in Gem file and no ruby sub-modules other than `devops_chef`
- `starpace_trainer`: python project and no ruby sub-modules other than `devops_chef`
- `damper`: python project and no ruby dependencies other than `devops_chef`

I am pretty sure this repo is no longer needed and is  probably much outdated by now; The last commit excluding the  maintenance related ones was made 7 years ago.

@Elikon do you have any reason to keep it around or should we bid adieu?

**Comment by quaelin** [comment]
Looks like it was just used by the machine-learning repo, which has itself been archived.
https://github.com/search?q=org%3Achange+aws-swf&type=Code

**Comment by mdimas** [comment]
All right, I'm going to archive it then.

**Pull request merged**
